config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.7
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/socib/Leaflet.TimeDimension:
      branch: master
      repo: https://github.com/socib/Leaflet.TimeDimension
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/socib/Leaflet.TimeDimension git:
        commands:
        - /usr/bin/env sh .sqa/script.hilly-cinnamon-javanese.sh
        container: qc.acc_breezy-aqua-pig
  QC.Doc:
    repos:
      github.com/socib/Leaflet.TimeDimension find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.hilly-goldenrod-hyena.sh
        container: qc.doc_dorky-black-dingo
      github.com/socib/Leaflet.TimeDimension git:
        commands:
        - /usr/bin/env sh .sqa/script.thirsty-cornflower-seahorse.sh
        container: qc.doc_shabby-tangerine-ocelot
      github.com/socib/Leaflet.TimeDimension markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.stealthy-blue-crab.sh
        container: qc.doc_wheezy-coral-sheepdog
  QC.Lic:
    repos:
      github.com/socib/Leaflet.TimeDimension licensee:
        commands:
        - /usr/bin/env sh .sqa/script.slaphappy-indigo-raccoon.sh
        container: qc.lic_cheeky-rust-falcon
  QC.Sty:
    repos:
      github.com/socib/Leaflet.TimeDimension jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.gamy-bronze-buffalo.sh
        container: qc.sty_gimpy-thistle-corgi
  QC.Ver:
    repos:
      github.com/socib/Leaflet.TimeDimension get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.cozy-vermilion-shrimp.sh
        container: qc.ver_paltry-asparagus-dragon
timeout: 5400
